site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - Concepts: index.md
    - Glossary: general/glossary.md
    - For Users:
        Getting Started: user/getting-started-for-users.md
        How to Search: user/how-to-search.md
        What Gets Searched: user/what-gets-searched.md
        Viewing Search Results: user/viewing-search-results.md
        $ Viewing Items: user/viewing-items.md
        $ Flagging Items for Later: user/recently-viewed.md
        Sharing Search Results: user/sharing.md
        Creating a PDF Report: user/pdf-report.md
        Using the Digital Notebook: user/digital-notebook.md
        Relationships: user/relationships.md
    - For Archivists:
        Getting Started: archivist/getting-started-arch.md
        Logging in: archivist/logging-in.md
        Relationships: archivist/relationships.md
        Add a new item: archivist/add-new-item.md
        $ Best Practices: archivist/best-practices.md
        Edit an existing item: archivist/edit-item.md
        Add a reference item: archivist/add-reference-item.md
        Delete an item: archivist/delete-item.md
        Field descriptions: archivist/field-descriptions.md
        Workflow fields: archivist/workflow-fields.md
        Working with relationships: archivist/working-with-relationships.md            
        About vocabularies: archivist/vocabularies.md
        Vocabulary Editor: archivist/vocabulary-editor.md
    - Administrator:
        FAQ: administrator/faq.md
        Omeka Elements: administrator/omeka-elements.md
        Import CSV data: administrator/import-csv.md
        Export PastPerfect data: administrator/pastperfect-export.md
        Zoomable images: administrator/zoomable-images.md
        $ Differences from Omeka: administrator/differences-from-omeka.md
    - Developer:
        Web server: developer/web-host.md
        MkDocs: developer/mkdocs.md
        File locations: developer/file-locations.md
        MySQL Workbench: developer/mysql-workbench.md
        Copy a MySQL database: developer/copy-mysql-db.md
        Install a Digital Archive site: developer/install-digital-archive.md
        GitHub: developer/github.md
        Python: developer/python.md
        Common Vocabulary Translator: developer/common-vocabulary-translator.md
        Site maintenance: developer/site-maintenance.md
        PHP development: developer/php-development.md
        Technologies: developer/technologies.md
    - Digital Archive plugins:
        AvantAdmin: plugins/avantadmin.md
        AvantCommon: plugins/avantcommon.md
        AvantCustom: plugins/avantcustom.md
        AvantDPLA: plugins/avantdpla.md
        AvantElasticsearch: plugins/avantelasticsearch.md
        AvantElements: plugins/avantelements.md
        AvantImport: plugins/avantimport.md
        AvantRelationships: plugins/avantrelationships.md
        AvantS3: plugins/avants3.md
        AvantSearch: plugins/avantsearch.md
        AvantVocabulary: plugins/avantvocabulary.md
        AvantZoom: plugins/avantzoom.md
    - Who this Documentation is for: general/documentation-categories.md

theme:
    name: readthedocs
    prev_next_buttons_location: bottom
    include_homepage_in_sidebar: true
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list