site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - User:
        - About relationships*: user/relationships.md
    - Archivist:
        - Items:
            - Add a new item: archivist/add-new-item.md
            - Edit an existing item*: archivist/edit-item.md
            - Add a reference item*: archivist/add-reference-item.md
            - Delete an item*: archivist/delete-item.md
        - Fields:
            - Field descriptions*: archivist/field-descriptions.md
            - Workflow fields: archivist/workflow-fields.md
    - Administrator:
        - Omeka: administrator/omeka.md
        - Zoomable images: administrator/zoomable-images.md
        - Plugins:
            AvantSearch: plugins/avantsearch/avantsearch.md
    - Superuser:
        - Web host administration: superuser/web-host.md
        - File Locations*: superuser/file-locations.md
        - MkDocs: superuser/mkdocs.md
        - MySQL Workbench: superuser/mysql-workbench.md
        - Beyond Compare*: superuser/beyond-compare.md
        - Install a Digital Archive site: superuser/install-digital-archive.md
    - Developer:
        - GitHub: developer/github.md
    - Welcome: index.md
    - Author's notes: author-notes.md
    
theme:
  name: windmill
    
# Customizations for the Windmill theme.
extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: true
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list