site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - User:
        - About relationships*: user/relationships.md
        - Searching*: user/search.md
    - Archivist:
        - Contents: archivist/contents.md
        - Items:
            - Add a new item: archivist/add-new-item.md
            - Edit an existing item*: archivist/edit-item.md
            - Add a reference item*: archivist/add-reference-item.md
            - Delete an item*: archivist/delete-item.md
        - Fields:
            - Field descriptions*: archivist/field-descriptions.md
            - Workflow fields: archivist/workflow-fields.md
        - Working with relationships*: archivist/working-with-relationships.md            
    - Administrator:
        - Omeka: administrator/omeka.md
        - Zoomable images: administrator/zoomable-images.md
    - Superuser:
        - Table of contents: superuser/contents.md
        - Web host administration: superuser/web-host.md
        - Import CSV data: superuser/import-csv.md
        - MySQL Workbench: superuser/mysql-workbench.md
        - Install a Digital Archive site: superuser/install-digital-archive.md
        - Subdomain installation: superuser/subdomain.md
        - Copy a MySQL database: superuser/copy-mysql-db.md
        - MkDocs: superuser/mkdocs.md
        - File Locations*: superuser/file-locations.md
    - Developer:
        - GitHub: developer/github.md
    - Digital Archive plugins:
        AvantAdmin: plugins/avantadmin.md
        AvantCommon: plugins/avantcommon.md
        AvantCustom: plugins/avantcustom.md
        AvantElasticsearch: plugins/avantelasticsearch.md
        AvantElements: plugins/avantelements.md
        AvantRelationships*: plugins/avantrelationships.md
        AvantS3: plugins/avants3.md
        AvantSearch*: plugins/avantsearch.md
        AvantZoom: plugins/avantzoom.md
    - Welcome: index.md
    - Author's notes: author-notes.md
    
theme:
  name: windmill
    
# Customizations for the Windmill theme.
extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: true
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list