site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - Getting Started: index.md
    - Glossary: glossary.md
    - For Users:
        Getting Started for Users: user/getting-started-user.md
        How to Search: user/how-to-search.md
        Viewing Search Results: user/viewing-search-results.md
        Viewing Items: user/viewing-items.md
        Viewing Related Items: user/viewing-related-items.md
        Flag Items to View Later: user/recently-viewed.md
        Share Search Results: user/sharing-search-results.md
        Create PDF Reports: user/pdf-report.md
        Use the Digital Notebook: user/digital-notebook.md
    - For Archivists:
        Getting Started for Archivists: archivist/getting-started-archivist.md
        Logging into the Digital Archive: archivist/logging-in.md
        Special Features for Archivists: archivist/special-features-archivist.md
        Working with Items: archivist/items.md
        Attach an Image or PDF to an Item: archivist/attach-file.md
        Add a Relationship to an Item: archivist/add-relationship.md
        What Gets Searched: archivist/what-gets-searched.md
        Common Vocabulary: archivist/common-vocabulary.md
        Vocabulary Editor: archivist/vocabulary-editor.md
        $ Best Practices: archivist/best-practices.md
    - Relationships:
        Getting Started with Relationships: relationships/getting-started-relationships.md
        Archive Relational Model: relationships/archive-relational-model.md
        Reference Items: relationships/reference-items.md
        Kinds of Relationships: relationships/kinds-of-relationships.md
        Relationship Types: relationships/relationship-types.md
        Relationship Rules: relationships/relationship-rules.md
    - Site Administration:
        $ Getting Started for Administrators: administrator/getting-started-administrator.md
        $ Omeka Administration: administrator/omeka-administration.md
        Add a New User: administrator/add-new-user.md
        Omeka Elements: administrator/omeka-elements.md
        Zoomable images: administrator/zoomable-images.md
        Import CSV data: administrator/import-csv.md
    - Technology:
        Common Vocabulary Translator: developer/common-vocabulary-translator.md
        Web server: developer/web-host.md
        MkDocs: developer/mkdocs.md
        File locations: developer/file-locations.md
        MySQL Workbench: developer/mysql-workbench.md
        Copy a MySQL database: developer/copy-mysql-db.md
        Install a Digital Archive site: developer/install-digital-archive.md
        GitHub: developer/github.md
        Python: developer/python.md
        Site maintenance: developer/site-maintenance.md
        PHP development: developer/php-development.md
        $ Technologies: developer/technologies.md
    - Digital Archive plugins:
        AvantAdmin: plugins/avantadmin.md
        AvantCommon: plugins/avantcommon.md
        AvantCustom: plugins/avantcustom.md
        AvantDPLA: plugins/avantdpla.md
        AvantElasticsearch: plugins/avantelasticsearch.md
        AvantElements: plugins/avantelements.md
        AvantImport: plugins/avantimport.md
        AvantRelationships: plugins/avantrelationships.md
        AvantS3: plugins/avants3.md
        AvantSearch: plugins/avantsearch.md
        AvantVocabulary: plugins/avantvocabulary.md
        AvantZoom: plugins/avantzoom.md

theme:
    name: readthedocs
    prev_next_buttons_location: bottom
    include_homepage_in_sidebar: true
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list