site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - User:
        #- Advanced search: user-advanced-search.md
        - About relationships*: user-relationships.md
    - Archivist:
        - Items:
            - Add a new item: arch-add-new-item.md
            - Edit an existing item*: arch-edit-item.md
            - Add a reference item*: arch-add-reference-item.md
            - Delete an item*: arch-delete-item.md
        - Fields:
            - Field descriptions*: arch-field-descriptions.md
            - Workflow fields: arch-workflow-fields.md
    - Administrator:
        - Zoomable images: admin-zoomable-images.md
    - Superuser:
        - MkDocs: super-mkdocs.md
        #- Passwords: super-passwords.md
        #- WordPress: super-wordpress.md
        #- Reclaim Hosting: super-reclaim-hosting.md
        #- File Locations: super-file-locations.md
        #- Elasticsearch: super-elasticsearch.md
        #- AWS S3: super-aws-s3.md
        #- Beyond Compare: super-beyond-compare.md
        #- cPanel: super-cpanel.md
    - Developer:
        #- Omeka: dev-omeka.md
        #- MySQL: dev-mysql.md
        #- MySQL Workbench: dev-mysql-workbench.md
        #- PHP Storm: dev-php-storm.md
        - GitHub: dev-github.md
    - Welcome: index.md
    - Author's notes: home-author-notes.md
    
theme:
  name: windmill
    
# Customizations for the Windmill theme.
extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: true
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list