site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - Welcome: index.md
    - Glossary: glossary.md
    - User:
        Searching: user/search.md
        Relationships: user/relationships.md
    - Archivist:
        Add a new item: archivist/add-new-item.md
        Edit an existing item: archivist/edit-item.md
        Add a reference item: archivist/add-reference-item.md
        Delete an item: archivist/delete-item.md
        Field descriptions: archivist/field-descriptions.md
        Workflow fields: archivist/workflow-fields.md
        Working with relationships: archivist/working-with-relationships.md            
        About vocabularies: archivist/vocabularies.md
        Vocabulary Editor: archivist/vocabulary-editor.md
    - Administrator:
        - FAQ: administrator/faq.md
        - Omeka Terminology: administrator/omeka-terminology.md
        - Omeka Elements: administrator/omeka-elements.md
        - Import CSV data: administrator/import-csv.md
        - Export PastPerfect data: administrator/pastperfect-export.md
        - Zoomable images: administrator/zoomable-images.md
    - Developer:
        Web server: developer/web-host.md
        MkDocs: developer/mkdocs.md
        File locations: developer/file-locations.md
        MySQL Workbench: developer/mysql-workbench.md
        Copy a MySQL database: developer/copy-mysql-db.md
        Install a Digital Archive site: developer/install-digital-archive.md
        Subdomain installation: developer/subdomain.md
        Bulk installation: developer/bulk-installation.md
        GitHub: developer/github.md
        Python: developer/python.md
        Common Facet Translator: developer/common-facet-translator.md
        Site maintenance: developer/site-maintenance.md
    - Digital Archive plugins:
        AvantAdmin: plugins/avantadmin.md
        AvantCommon: plugins/avantcommon.md
        AvantCustom: plugins/avantcustom.md
        AvantDPLA: plugins/avantdpla.md
        AvantElasticsearch: plugins/avantelasticsearch.md
        AvantElements: plugins/avantelements.md
        AvantImport: plugins/avantimport.md
        AvantRelationships: plugins/avantrelationships.md
        AvantS3: plugins/avants3.md
        AvantSearch: plugins/avantsearch.md
        AvantVocabulary: plugins/avantvocabulary.md
        AvantZoom: plugins/avantzoom.md
    
theme:
    name: readthedocs
    prev_next_buttons_location: top
    include_homepage_in_sidebar: false
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list