site_name: Digital Archive Docs
copyright: 'Copyright &copy; 2020 AvantLogic Corporation'

nav:
    - Welcome: index.md
    - User:
        - About relationships*: user/relationships.md
        - Searching*: user/search.md
    - Archivist:
        - Contents: archivist/contents.md
        - Items:
            - Add a new item: archivist/add-new-item.md
            - Edit an existing item*: archivist/edit-item.md
            - Add a reference item*: archivist/add-reference-item.md
            - Delete an item*: archivist/delete-item.md
        - Fields:
            - Field descriptions*: archivist/field-descriptions.md
            - Workflow fields: archivist/workflow-fields.md
        - Working with relationships*: archivist/working-with-relationships.md            
    - Administrator:
        - Table of contents: administrator/contents.md
        - Omeka: administrator/omeka.md
        - Import CSV data: administrator/import-csv.md
        - Zoomable images: administrator/zoomable-images.md
    - Developer:
        - Table of contents: developer/contents.md
        - Web host administration: developer/web-host.md
        - MySQL Workbench: developer/mysql-workbench.md
        - Install a Digital Archive site: developer/install-digital-archive.md
        - Subdomain installation: developer/subdomain.md
        - Copy a MySQL database: developer/copy-mysql-db.md
        - MkDocs: developer/mkdocs.md
        - File Locations*: developer/file-locations.md
        - GitHub: developer/github.md
    - Digital Archive plugins:
        AvantAdmin: plugins/avantadmin.md
        AvantCommon: plugins/avantcommon.md
        AvantCustom: plugins/avantcustom.md
        AvantDPLA: plugins/avantdpla.md
        AvantElasticsearch: plugins/avantelasticsearch.md
        AvantElements: plugins/avantelements.md
        AvantImport: plugins/avantimport.md
        AvantRelationships*: plugins/avantrelationships.md
        AvantS3: plugins/avants3.md
        AvantSearch*: plugins/avantsearch.md
        AvantZoom: plugins/avantzoom.md
    
theme:
  name: windmill
    
# Customizations for the Windmill theme.
extra:
  history_buttons: false
  article_nav_top: false
  article_nav_bottom: true
  
extra_css:
    - css/extra.css  

markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - def_list